model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_mask.VQMaskModel
  params:
    embed_dim: 256
    n_embed: 256
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: taming.data.lrw.LRWTrain
      params:
        training_images_list_file: configs/talking_config/lrw_train.yaml
        size: 256
        with_mask: True
        random_mask_config:
          target: taming.data.augmentation.RandomMaskGenerator
          params:
            isTrain: True
            size: 256
            patch: 8
    # validation:
    #   target: taming.data.lrw.LRWTest
    #   params:
    #     test_images_list_file: configs/talking_config/lrw_val.yaml
    #     size: 256

