model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_pp.VQPPModel
  params:
    teacher_config:
      base_learning_rate: 4.5e-6
      target: taming.models.vqgan.VQModel
      params:
        embed_dim: 256
        n_embed: 8192
        ckpt_path: PRETRAIN/teacher_pretrain/last.ckpt
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
          c_channels: 3
          
        lossconfig:
          target: taming.modules.losses.vqperceptual.DummyLoss
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    num_workers: 6
    train:
      target: taming.data.lrw.LRWTrain
      params:
        training_images_list_file: configs/talking_config/lrw_train_pc.yaml
        size: 256
        with_mask: True
        random_mask_config:
          target: taming.data.augmentation.RandomMaskGenerator
          params:
            isTrain: False
            size: 256
            patch: 8
    validation:
      target: taming.data.lrw.LRWTest
      params:
        test_images_list_file: configs/talking_config/lrw_val.yaml
        size: 256
        with_mask: True
        random_mask_config:
          target: taming.data.augmentation.RandomMaskGenerator
          params:
            isTrain: False
            size: 256
            patch: 8
