model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqref.VQRefModel
  params:
    teacher_config:
      base_learning_rate: 4.5e-6
      target: taming.models.vqgan.VQModel
      params:
        embed_dim: 256
        n_embed: 8192
        ckpt_path: PRETRAIN/new_teacher_pretrain/last.ckpt
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
          c_channels: 3
          
        lossconfig:
          target: taming.modules.losses.vqperceptual.DummyLoss

    unetconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      c_channels: 6

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 6
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0
        disc_loss: "hinge"
        D_type: 'multiscale'
        mask_loss: True
        multiframe_D: True
    maskz: False
    # ckpt_path: logs/2022-02-19T01-50-25_vqpp_double/checkpoints/epoch=1-step=39999.ckpt
    # ignore_keys: ['loss.discriminator']

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 6
    train:
      target: taming.data.lrw.LRWTrain
      params:
        training_images_list_file: configs/talking_config/lrw_train.yaml
        size: 256
        with_mask: True
        random_mask_config:
          target: taming.data.augmentation.RandomMaskGenerator
          params:
            isTrain: True
            size: 256
            patch: 8