dataset:
  frame_interval: 2
  clip_len: 1
  num_clips: 1
  num_frames_per_clip: 5
  hop_size: 160
  crop_size: 256
  load_frames: True
  load_input: False
  load_audio: True
  datatype: lrw
  img_lmdb_paths: ['/root/paddlejob/workspace/zhouhang/lrw/imgs/0_100/',
                    # '/root/paddlejob/workspace/zhouhang/lrw/imgs/100_200/',
                    # '/root/paddlejob/workspace/zhouhang/lrw/imgs/200_300/',
                    # '/root/paddlejob/workspace/zhouhang/lrw/imgs/300_400/',
                    # '/root/paddlejob/workspace/zhouhang/lrw/imgs/400_500/'
                    ]
  audio_lmdb_paths: []
  num_inputs: 1
  load_word_label: True
  data_ratio_per_epoch: 1
  load_ref: True
